url: "https://jcksanderson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jack Sanderson" # the name of your site, e.g. ACME Corp.
description: "CS + Stats @ UChicago"
