menu:
- {name: 'about', url: '/about'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/assets/cv.pdf'}
- {name: 'productivity', url: '/productivity'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Discrete Math', url: 'discrete-math'}

social:
- {icon: 'github', link: 'https://github.com/jcksanderson'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jcksanderson'}

# contacts:
# - {name: 'Jack Sanderson', title: 'Undergraduate Student', department: 'Computer Science & Statistics', institution: 'University of Chicago', email: 'jacksanderson@uchicago.edu', image: 'assets/img/contact.png'}
